# Generated by Django 6.0.4 on 2026-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Blood Pressure'),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='sugar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Blood Sugar'),
        ),
        migrations.AddField(
            model_name='visit',
            name='temp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='visit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
