# Generated by Django 6.0.4 on 2026-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_bp_visit_follow_up_date_visit_sugar_visit_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('content', models.TextField(verbose_name='Medication Details')),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BP'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prescription_text',
            field=models.TextField(verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sugar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sugar'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='symptoms',
            field=models.TextField(verbose_name='Symptoms'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='temp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Temp'),
        ),
    ]
