# Generated by Django 6.0.4 on 2026-04-21 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_uuid_alter_patient_blood_group_and_more'),
        ('visits', '0003_prescriptiontemplate_alter_visit_bp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Attended By'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Follow-up Date'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prescription_photo',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/', verbose_name='Prescription Photo'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Visited On'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
    ]
