# Generated by Django 6.0.4 on 2026-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('unexamined', 'Unexamined')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
