# Generated by Django 6.0.4 on 2026-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_path', models.CharField(default='/data/data/com.termux/files/home/backups/', max_length=500, verbose_name='Backup Storage Path')),
                ('last_backup_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Backup Date')),
                ('auto_backup_days', models.IntegerField(default=10, verbose_name='Auto Backup Frequency (Days)')),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
    ]
