# Generated by Django 6.0.4 on 2026-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='security_pin',
            field=models.CharField(default='5741', max_length=4, verbose_name='Security PIN'),
        ),
    ]
